### ISSUE TITLE
Snowpack SSR compatible?

### ISSUE THREAD

**Issue by janosh** [metonym/svelte-highlight#130]
Can svelte-highlight be used with the Snowpack bundler used in `svelte@next`? After

```sh
npm init svelte@next my-app && cd my-app && npm i && npm i -D svelte-highlight
```

I'm getting this error:

> [snowpack] Error: <Highlight> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

from the code below

```svelte
<script>
  import { Highlight } from "svelte-highlight";
  import { typescript } from "svelte-highlight/languages";
  import "svelte-highlight/styles/github.css";

  $: code = `const add = (a: number, b: number) => a + b;`;
</script>

<Highlight language="{typescript}" {code} />
```

**Comment by metonym** [comment]
@janosh  Hi, thank you for raising an issue.

I was able to reproduce your error.

I haven't worked much with Snowpack, but from my understanding it attempts to automatically detect and optimize package entry points.

For `svelte-highlight` in particular, there are multiple entry points, for the compiled Svelte code along with the `highlight.js` languages and styles (CSS + JS). However, `svelte-highlight` does support the ESM format for each of these entry points.

Could you try the following workaround of explicitly setting the path to import the ESM code (`index.mjs`)?

```svelte
<script>
  import { Highlight } from "svelte-highlight/lib/index.mjs";
  import { typescript } from "svelte-highlight/languages/index.mjs";
  import "svelte-highlight/styles/github.css";

  $: code = `const add = (a: number, b: number) => a + b;`;
</script>

<Highlight language={typescript} {code} />
```

**Comment by metonym** [comment]
I was able to run this with the default Snowpack Svelte template. I added the [example](https://github.com/metonym/svelte-highlight/tree/master/examples/snowpack) to the repo.

Unfortunately, I wasn't able to get it working with `svelte@next`.

**Comment by janosh** [comment]
Thanks for giving it a try! Feel free to close this issue if you think there's nothing more to do atm.

**Comment by metonym** [comment]
Updated the [snowpack example](https://github.com/metonym/svelte-highlight/tree/master/examples/snowpack):

- upgraded snowpack to version 3
- upgrade svelte-highlight to version 1

It should work as expected now without any vexing workaround.
