### ISSUE TITLE
HTML and CSS support?

### ISSUE THREAD

**Issue by bbaki** [metonym/svelte-highlight#145]
I'm not sure if I'm missing something but is HTML and CSS supported?
Thanks,

**Comment by metonym** [comment]
From the list of supported languages:

- use [xml](https://github.com/metonym/svelte-highlight/blob/master/SUPPORTED_LANGUAGES.md#xml-xml) for HTML
- [css](https://github.com/metonym/svelte-highlight/blob/master/SUPPORTED_LANGUAGES.md#css-css)

**Comment by bbaki** [comment]
Great many thanks, `css` was in fact on the list I'll be honest I haven't searched for it there I've added it to the question as an afterthought. My main concern was for HTML, it kind of makes sens to use XML for that, I guess it might make sense to add an information about this in the `SUPPORTED_LANGUAGES.md` file to make it easy for `ctrl + f` search.

Cheers
