### ISSUE TITLE
[feature] Add a way to target code blocks by language at runtime

### ISSUE THREAD

**Issue by willster277** [metonym/svelte-highlight#170]
#### What's the goal?

I've been using this library in a non-production site to see what it can and cant do. I've had the idea of adding a pseudo element that places a language identifier in one corner of the code block to clearly differentiate between languages with similar syntax.

![example of JS language identifier](https://user-images.githubusercontent.com/85991558/132945248-e40a08bb-163f-4ee3-b302-665626b951c8.png)

#### What's the problem?

Unfortunately, the only way I've been able to do this is by applying some custom props to either an element containing the highlight component (which is difficult to maintain) or scoping it to a `__layout.svelte` for the route, which is less than ideal when you want multiple languages in the same page eg html css and js.
Of course, theres the option of utilising the `$$restProps`, but that has a similar maintainability issue as custom props around the highlight component.

#### What's the solution?

The solution would be to simply add either a class (not preferred) or an attribute such as `data-language` (preferred) to the `<pre />`, which would be determined differently for each component;

`<Highlight />` - using the existing `.name` on `language` we can determine what language is used;
```html
  <pre
    class:hljs="{true}"
+   data-language="{language.name || ''}"
    {...$$restProps}>
```

`<HighlightAuto />` - using the existing `hljs.highlightAuto(code)`'s return value, we can get the `.language` as follows;
```html
<script>
  // ...
  let highlighted = undefined;
+ let language = undefined;

  $: if (code) {
+   ({ value: highlighted, language } = hljs.highlightAuto(code));
  }
</script>

<slot highlighted="{highlighted}">
  <pre
    class:hljs="{true}"
+   data-language="{language || ''}"
    {...$$restProps}>
    <!-- ... -->
```

`<HighlightSvelte />` - by far the easiest, it's svelte;
```html
  <pre
    class:hljs="{true}"
+   data-language="svelte"
    {...$$restProps}>
    <!-- ... -->
```

#### What problems does the solution cause?

- Shipping additional code and running additional code
Given how little it is though, I feel it's not anything to be concerned about, after all svelte only ships one copy of a component, and the cost of the few insertions is extremely small.

- Probably wont work on IE <=11
Does anything? Pretty sure IE is going to be almost completely gone very soon anyway.

- Confusion for newcomers
I don't think it will confuse anyone to see `data-language="javascript"` on a JS codeblock, and for people with experience in highlight.js it will also make sense.

- The image above shows "js", but the language names are full form eg "javascript"
This isn't an issue for my use case as I can have any text I need in the language identifier. Its possible to have a second attribute `data-lang` with the shorthand, but that would likely be more code and effort than its worth.

#### Am I willing to implement this and make a PR?

Absolutely. I'm happy to implement and test this if you're happy for the feature to be added.

**Comment by metonym** [comment]
This is a great idea and a thorough write-up. Please feel free to submit a PR.

**Comment by willster277** [comment]
Awesome, thank you.
I'll work on this here and there and submit the PR when it's ready.
