### ISSUE TITLE
[bug] Multiple issues regarding styling (linked to v3.4.0)

### ISSUE THREAD

**Issue by willster277** [metonym/svelte-highlight#172]
I noticed a bug around my recent PR that hadn't shown up in testing, I suspect it's appearance now is to do with a difference between my own project (where I discovered the bug) and the `/demo` project (where I did my development testing).

As it's my code that's bugged, and as I found it, I should probably get a fix done and ensure that anything that arises as a consequence is both fixed and acceptable to go into v3.4.1.

I have forked this repo and dug into the bug and I've written up my  findings in full [on this gist](https://gist.github.com/willster277/c1541a62f7f9cd05029965d1d42d3a92) containing information on the code, issues, solutions, and side effects. It's quite long (my apologies), but should be plenty of detail to convey what problems my recent PR has caused/highlighted.

Below I'll be summarising what I've found.

### Bug 1 - Mismatched Classes

The use of the `.hljs` class deviates from the intended use from `highlight.js` .

 As to not require a major version, I suggest simply adding the `.hljs` class to the `<code />` as well as leaving it on the `<pre />` .

Fix causes bug 3, fix causes bug 4

### Bug 2 - Over Padded "langtags"

A small mistake was made when implementing langtags, and the padding was too large. 

I suggest changing the padding by the 4px it is off by.

Fix highlights bug 4

### Bug 3 - Mismatched Classes (cont.)

The css preprocessing done on `ScopedStyle` components in the `/demo` project causes some issues in the resulting CSS. 

I suggest modifying one of the replacements to fix both of the issues.

Fix highlights bug 4

### Bug 4 - Demo Project CSS

Fixing the previous three bugs has caused the `/demo` project's CSS to become partly outdated, requiring a refresh. 

I suggest moving all styles from `.hljs code` to `pre.hljs` and removing padding from `pre.hljs`.

### Am I willing to implement this and make a PR?

If this bugfix request is accepted I'm happy to put in the work.

(This time with more rigorous testing to prevent blunders like bug 2)

**Comment by metonym** [comment]
Again – the thorough breakdown is much appreciated.

> The use of the .hljs class deviates from the intended use from highlight.js .

> As to not require a major version, I suggest simply adding the .hljs class to the <code /> as well as leaving it on the <pre /> .

It seems you're right, the `.hljs` class should only be applied to the `code` element. I think this would warrant a major version bump, which I'm completely fine with so longs as it fixes the underlying issue.

I'd definitely appreciate any PR to help fix this.

**Comment by willster277** [comment]
Awesome, I'll get started on the fixes with the breaking change included.

We can always modify the PR to be non-breaking if needed as the fixes are quite similar either way.
