### ISSUE TITLE
SyntaxError: Indirectly exported binding name 'default' cannot be resolved by star export entries.

### ISSUE THREAD

**Issue by MathieuNolot** [metonym/svelte-highlight#193]
The following import:
import Highlight from "svelte-highlight";
Produce the following error message on console log:
SyntaxError: Indirectly exported binding name 'default' cannot be resolved by star export entries.
(installed with npm i -D svelte-highlight and Vite)

**Comment by metonym** [comment]
Can you provide a minimal repro? I've tried using Vite and NPM and was not able to recreate the message.

```json
{
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build"
  },
  "devDependencies": {
    "@sveltejs/vite-plugin-svelte": "next",
    "svelte": "^3.46.4",
    "svelte-highlight": "^5.2.1",
    "vite": "^2.8.4"
  }
}

```

```svelte
<script>
  import Highlight from "svelte-highlight/src/Highlight.svelte";
  import typescript from "svelte-highlight/src/languages/typescript";
  import atomOneDark from "svelte-highlight/src/styles/atom-one-dark";

  const code = "const add = (a: number, b: number) => a + b;";
</script>

<svelte:head>
  {@html atomOneDark}
</svelte:head>

<Highlight language={typescript} {code} />

```

**Comment by metonym** [comment]
@MathieuNolot I noticed that it wasn't working in the Svelte REPL.

I've reverted to using the default export from `highlight.js` in #194.

Try version 5.2.2; hopefully it also addresses your issue.

[Working REPL](https://svelte.dev/repl/e9c59b1d029a49e0b89d296ffc33555b?version=3.46.4)

**Comment by metonym** [comment]
I'm closing this issue – the repo has a [working Vite example](https://github.com/metonym/svelte-highlight/tree/master/examples/vite). If this issue persists, feel free to re-open with a repro.
