### ISSUE TITLE
Add dynamic import example

### ISSUE THREAD

**Issue by metonym** [metonym/svelte-highlight#219]
This is less of an issue for SvelteKit which will already code-split your app.

However, for other SPA set-ups, it would be nice to have a quick primer on dynamically importing a language grammar, which can be quite heavy.

**Comment by mcndt** [comment]
+1 on this. Currently trying to solve this issue for a project where codeblocks are rendered client-side after the code is decrypted.

**Comment by metonym** [comment]
A [recipe for code-splitting](https://github.com/metonym/svelte-highlight#code-splitting) is now documented in the README. In addition, a `DynamicImport` component has been added to each example set-up.

The nice thing about SvelteKit/Vite/Webpack is that code-split the build with zero-configuration. The Rollup example needed a few [tweaks to the rollup.config.js](https://github.com/metonym/svelte-highlight/commit/c179b55e8e7774d7fc04a925fed53cb7c6353a14#diff-4ca00fdd91b6f0ebb552131c6e870cc9611392c3247eac4046f75974d77fe532).

```svelte
<script>
  import { onMount } from "svelte";

  let component;
  let styles;

  onMount(async () => {
    component = (await import("svelte-highlight")).HighlightAuto;
    styles = (await import("svelte-highlight/styles/github")).default;
  });
</script>

<svelte:head>
  {#if styles}
    {@html styles}
  {/if}
</svelte:head>

<svelte:component
  this={component}
  langtag
  code={`body {\n  padding: 0;\n  color: red;\n}`}
/>
```

As a result, the code is split into chunks, which can improve performance.

<img width="1361" alt="dynamic-import" src="https://user-images.githubusercontent.com/10718366/183301630-6541c1fa-3be5-43bd-b562-5595c34b56f1.png">
