### ISSUE TITLE
Highlighting data returned from fetch

### ISSUE THREAD

**Issue by carlskii** [metonym/svelte-highlight#236]
So I need to highlight some date retuned from a remote endpoint using fetch. Could you show and example for hi-lighting the JSON returned in this REPL example:

https://svelte.dev/repl/a74f1ed8e3eb4aec82cb743e13443ee4?version=3.48.0

**Comment by carlskii** [comment]
Thanks very much. I thought I tried this, but must have been doing something stupid. If I want to highlight  an editable div before sending it as the fetch POST body/data. Is there a best way to do this ? I'm still trying to learn Svelte, so some of the concepts are new to me.

**Comment by metonym** [comment]
If you're seeking a proper code editor, I would recommend [CodeMirror](https://github.com/codemirror/codemirror5), which is what I believe the Svelte REPL uses. I don't think this library serves as an appropriate text editor.

Another example is [sveld](https://sveld.onrender.com/) uses both CodeMirror and Svelte Highlight. The editable content on the left is powered by CodeMirror while the static text on the right is highlighted by this library.

![sveld UI](https://user-images.githubusercontent.com/10718366/188932368-1223fe76-dadd-47e6-bd24-df64c2896624.png)

**Comment by carlskii** [comment]
Thanks for the direction here. I took a look at this. I couldn't seem to find any examples for `sveld`. Also these might be an overkill for my use case at this stage. I will be repopulating the content for the POST body  and only need to change a couple of the values, so really just looking for something super easy for now - Especially since I'm still trying to learn svelt. 

Really just to hook a button up to the div content and have it sent to fetch.

**Comment by carlskii** [comment]
Arh - I can see the screenshot is an example. I will take a look now.

**Comment by metonym** [comment]
Code editor: https://github.com/carbon-design-system/sveld/blob/main/playground/CodeEditor.svelte
Code highlighter: https://github.com/carbon-design-system/sveld/blob/main/playground/CodeHighlighter.svelte

**Comment by carlskii** [comment]
Excellent. Thanks again. Is there a way to easily hook these up to the input and output of `fetch` ?  i.e. Have the content of the editor sent as a POST and then hi-light the response.

**Comment by metonym** [comment]
No – you would have to use the `highlight.js` API directly.

https://github.com/metonym/svelte-highlight/blob/c29cf2010a235749defdff6408bb82a6c51ffd72/src/Highlight.svelte#L80-L81
