### ISSUE TITLE
What is the rollup equivalent

### ISSUE THREAD

**Issue by pjebs** [metonym/svelte-highlight#239]
```
optimizeDeps: {
    include: ["highlight.js", "highlight.js/lib/core"],
  },

```

I'm using only rollup (no sveltekit). It doesn't seem to understand this config.

**Comment by metonym** [comment]
Rollup doesn't use/require `optimizeDeps`. See the [example Rollup set-up](https://github.com/metonym/svelte-highlight/tree/b5d7de3257bb41d19e09ab676367bfdd2c6e3b5c/examples/rollup).
