### ISSUE TITLE
Word wrap long strings?

### ISSUE THREAD

**Issue by silverbucket** [metonym/svelte-highlight#243]
I am using Svelte Highlight to display some JSON, however some of the properties are very long strings, these go off the screen and I have tried a number of CSS rules on the parent div to wrap the words, with no luck. Is there a way to tell Highlight to wrap long strings?

**Comment by metonym** [comment]
The native `pre` element has a `white-space: pre;` rule to preserve the formatting of child text.

Try applying `white-space: pre-wrap;` on the `pre` element to override this behavior.

**Comment by silverbucket** [comment]
Forgot to follow up, this fix worked. Thanks!
