### ISSUE TITLE
Support highlighted lines using `LineNumbers`

### ISSUE THREAD

**Issue by metonym** [metonym/svelte-highlight#256]
It would be nice if specific lines could be highlighted in the `LineNumbers` component.

A prop called `highlightedLines` could accept an array of line indices to highlight (zero-indexed).

```svelte
<LineNumbers {highlighted} highlightedLines={[0, 1]} />
```

A custom color could be applied through a style prop.

```svelte
<LineNumbers
  {highlighted}
  highlightedLines={[0, 1]}
  --highlighted-background="rgba(255, 255, 255, 0.4)"
/>
```

**Comment by megmut** [comment]
+1, this would be cool!
