### ISSUE TITLE
Bug: padding-bottom is 1em when line is not last

### ISSUE THREAD

**Issue by pjebs** [metonym/svelte-highlight#258]
@metonym 
You can see in the screenshot that `line 890` has padding-bottom set to `1em` despite not being the last line of code.

The solution is to remove `@const` from below lines:
https://github.com/metonym/svelte-highlight/blob/master/src/LineNumbers.svelte#L86

It interferes with the reactivity of the `code` prop which could have varying numbers of lines.

![image](https://user-images.githubusercontent.com/5377970/210170678-f5763eda-42ca-4006-9d70-86d51aaf138c.png)

**Comment by metonym** [comment]
Fixed in [v7.1.2](https://github.com/metonym/svelte-highlight/releases/tag/v7.1.2)
