### ISSUE TITLE
Auto new line

### ISSUE THREAD

**Issue by nicholasmordecai** [metonym/svelte-highlight#265]
> not an issue - possible a feature request?

Not sure if this is even possible with highlight.js, but is there any way to automatically format code? For example:

```ts 
const code = `const add = (a: number, b: number) => a + b;`;
```
Produces: 
<img width="656" alt="Screenshot 2023-01-24 at 12 46 18" src="https://user-images.githubusercontent.com/10081046/214295214-c77078c7-fa3a-4c8f-be82-7344f0cf8501.png">

```ts 
const code = `const add = (a: number, b: number) => a + b; let foo: string = 'bar';`;
```
Produces:
<img width="739" alt="Screenshot 2023-01-24 at 12 46 55" src="https://user-images.githubusercontent.com/10081046/214295320-97143678-e4b4-4019-af54-4d5ee720c82a.png">

But I have a unique use case where it would be advantageous for it to look like this:
<img width="655" alt="Screenshot 2023-01-24 at 12 47 58" src="https://user-images.githubusercontent.com/10081046/214295588-224e8ca8-dcba-47d1-a89d-79c834a8467b.png">

I was able to achieve this by using a new line string:
```ts
const code = `const add = (a: number, b: number) => a + b; \nlet foo: string = 'bar';`;
```
But it's a little clunky.

Maybe I'm asking for the earth and this is far out of the scope of highlight.js / svelte-highlight but was wondering if you knew if this was possible?

Cheers

**Comment by geerew** [comment]
Im not the developer but I wouldn't recommend implmenting a feature like this as there are many scenarios whereby this would incorrectly split, for example

* Your code may declare 2 variables on the same line (`var a =1; var b = 2;`), which is ugly, but possibly how it appears in the codebase
* You could have a string with `;` .. `fmt.Println(hello; how; are; you;`

There would be other edge cases too

Just my 2 cents

**Comment by metonym** [comment]
I agree with @geerew. I think that code formatting is beyond the scope of this library.

I would recommend looking at Prettier to format code, which can run in both Node and the [browser](https://prettier.io/docs/en/browser.html#usage).

Note that using Prettier in the browser will increase the JS bundle size by a significant amount; I wrote a [Svelte preprocessor](https://github.com/metonym/svelte-preprocess-highlight) that both formats and highlights code in Node.js to avoid the runtime costs of shipping both `highlight.js` and `prettier`.
