### ISSUE TITLE
Add missing Svelte exports condition

### ISSUE THREAD

**Issue by blueneogeo** [metonym/svelte-highlight#307]
From https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition:

### missing exports condition

| If you see a warning logged for this when using a Svelte library, please tell the library maintainers.

Using the `svelte` field in `package.json` to point at `.svelte` source files is **deprecated** and you must use a `svelte` [export condition](https://nodejs.org/api/packages.html#conditional-exports).
vite-plugin-svelte 3 still resolves it as a fallback, but in a future major release this is going to be removed and without exports condition resolving the library is going to fail.

Example:

```diff
// package.json
  "files": ["dist"],
  "svelte": "dist/index.js",
+ "exports": {
+   ".": {
+     "svelte": "./dist/index.js"
+   }
  }
```

**Comment by metonym** [comment]
I'll take a look.

**Comment by metonym** [comment]
Fixed in [v7.4.3](https://github.com/metonym/svelte-highlight/releases/tag/v7.4.3)

**Comment by metonym** [comment]
Note: I encountered some rough edges when attempting to use it with TypeScript and Rollup.

**If you're reading this**, make sure to use [v7.4.6](https://github.com/metonym/svelte-highlight/releases/tag/v7.4.6).

Fixes include:

- Explicit paths for type definitions
- Explicit file extension for `.css` files
- Correctly mapping `./*svelte` for direct component imports

**Comment by blueneogeo** [comment]
Thank you for the quick fix
