### ISSUE TITLE
Svelte Highlight incompatable with Svelte Flickering while using the circular option.

### ISSUE THREAD

**Issue by BadPingHere** [metonym/svelte-highlight#309]
As the title says, when using [svelte-flickering](https://github.com/naver/egjs-flicking/blob/master/packages/svelte-flicking/README.md), and encompassing a panel with a code block, it flickers between different div's, and has a drastic change in transformations. This occurs on any type of codeblock, no matter the configuration, as long as the circular:true is applied to the flicking options. I believe this a highlight bug rather than a flicking bug due to it being broken with all codeblocks, and working with basically anything else. A gif of this in action is added below.
![firefox_KowrH4IjJ1](https://github.com/metonym/svelte-highlight/assets/62813557/e3ac2e19-c100-46d7-bbf7-25a9521cb351)

**Comment by metonym** [comment]
- What version of `svelte-highlight`?
- Could you provide a minimal repro? Even sample code without a full repo reproduction would be helpful.

**Comment by BadPingHere** [comment]
I'm currently on Svelte-Highlight v7.4.2, along with Svelte-Flicking v4.11.2. I've also uploaded a minimal repo [here](https://github.com/BadPingHere/minimal-repoduction/tree/main).

**Comment by metonym** [comment]
Thanks. In your repro, I removed the Highlight components and just rendered the text. Without using svelte-highlight at all, the same bug happens.

As such, I'm inclined to believe this is a bug with the Flicking library.

See here: https://stackblitz.com/edit/github-ccvn67?file=package.json,src%2Froutes%2F%2Bpage.svelte

**Comment by BadPingHere** [comment]
Yeah, im seeing what you're seeing.
