### ISSUE TITLE
Fix self-closing div tags

### ISSUE THREAD

**Issue by mhkeller** [metonym/svelte-highlight#341]
Svelte 5 throws a warning if you use self-closing div tags:

```
node_modules/svelte-highlight/LineNumbers.svelte:48:14 Self-closing HTML tags for non-void elements are ambiguous — use `<div ...></div>` rather than `<div ... />`
node_modules/svelte-highlight/LineNumbers.svelte:57:14 Self-closing HTML tags for non-void elements are ambiguous — use `<div ...></div>` rather than `<div ... />
```

It would help cut down on warning messages I'm getting (and other folks will get in the future) by adding a `</div>` where needed.

**Comment by metonym** [comment]
Thank you for flagging. I will take a look.

**Comment by metonym** [comment]
Fixed in [https://github.com/metonym/svelte-highlight/releases/tag/v7.6.1](v7.6.1)

**Comment by mhkeller** [comment]
Thanks for putting this in so quickly!
