### ISSUE TITLE
Request to add cURL language

### ISSUE THREAD

**Issue by Loizzus** [metonym/svelte-highlight#352]
Could you add the cURL language plugin from here?
https://github.com/highlightjs/highlightjs-curl

Or how do we add plugins?

**Comment by metonym** [comment]
Hi there. I'd recommend installing `highlightjs-curl` and passing it as a [custom language](https://github.com/metonym/svelte-highlight?tab=readme-ov-file#custom-language).

```svelte
<script>
  import { Highlight } from "svelte-highlight";
  import curl from "highlightjs-curl";
  import atomOneDark from "svelte-highlight/styles/atom-one-dark";

  const language = {
    name: "curl",
    register: curl,
  };

  const code = `curl -X POST "https://api.example.com/data" \\
     -H "Content-Type: application/json" \\
     -d '{"key": "value"}'`;
</script>

<svelte:head>
  {@html atomOneDark}
</svelte:head>

<Highlight {language} {code} />

```

This produces the following using a minimal SvelteKit set-up:

<img width="659" alt="Screenshot 2024-11-12 at 8 06 29 PM" src="https://github.com/user-attachments/assets/173cffb0-8bd3-4205-906f-5f2a63306f5e">

**Comment by Loizzus** [comment]
Thank you that worked very well!
